# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9346389e065bee6dd226f0d504c6fcc16f7b0a952a7c03f3ef4a5ad301ca61d62e672889497eca45f997ad7867fd081ab941d8636c7ec571856db42b9b309e4

test:
  secret_key_base: 01acdb1e62985c4940517e3d737aac7ca12f6d246316907e904d6cdff9a3dae7bbef7b8717a6c4bb9b30d9e4b457ca3d5db6aa53ff411ed7885762ca232c306a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
